### ISSUE TITLE
Error when running vignettes code: `Error: File cached locally seems to be corrupted`

### ISSUE THREAD

**Issue by barracuda156** [ipeaGIT/censobr#48]
```
--->  Testing R-censobr
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-censobr/R-censobr/work/censobr-0.3.2" && /opt/local/bin/R CMD check ./censobr_0.3.2.tar.gz --no-manual --no-build-vignettes 
* using log directory ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-censobr/R-censobr/work/censobr-0.3.2/censobr.Rcheck’
* using R version 4.4.1 (2024-06-14)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* R was compiled by
    gcc-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0
    GNU Fortran (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0
* running under: OS X Snow Leopard 10.6
* using session charset: UTF-8
* using options ‘--no-manual --no-build-vignettes’
* checking for file ‘censobr/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘censobr’ version ‘0.3.2’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘censobr’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking whether startup messages can be suppressed ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking files in ‘vignettes’ ... WARNING
Files in the 'vignettes' directory but no files in 'inst/doc':
  ‘censobr.Rmd’ ‘census_tracts_data.Rmd’ ‘documentation.Rmd’
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... WARNING
Directory 'inst/doc' does not exist.
Package vignettes without corresponding single PDF/HTML:
  ‘censobr.Rmd’
  ‘census_tracts_data.Rmd’
  ‘documentation.Rmd’
* checking running R code from vignettes ...
  ‘censobr.Rmd’ using ‘UTF-8’... failed
  ‘census_tracts_data.Rmd’ using ‘UTF-8’... failed
  ‘documentation.Rmd’ using ‘UTF-8’... OK
 ERROR
Errors in running code in vignettes:
when running code in ‘censobr.Rmd’
  ...
> library(ggplot2)

> pop <- read_population(year = 2010, columns = c("abbrev_state", 
+     "V0606", "V0010", "V6400"), add_labels = "pt", showProgress = FALSE)
Downloading data and storing it locally for future use.

  When sourcing ‘censobr.R’:
Error: File cached locally seems to be corrupted. Please download it again using 'cache = FALSE'.
Alternatively, you can remove the corrupted file with 'censobr::censobr_cache(delete_file = "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-censobr/R-censobr/work/.home/Library/Caches/org.R-project.R/R/censobr/data_release_v0.3.0/2010_population_v0.3.0.parquet")'
Execution halted
when running code in ‘census_tracts_data.Rmd’
  ...
> library(censobr)

> dom <- read_tracts(year = 2010, dataset = "Domicilio", 
+     showProgress = FALSE)
Downloading data and storing it locally for future use.

  When sourcing ‘census_tracts_data.R’:
Error: File cached locally seems to be corrupted. Please download it again using 'cache = FALSE'.
Alternatively, you can remove the corrupted file with 'censobr::censobr_cache(delete_file = "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-censobr/R-censobr/work/.home/Library/Caches/org.R-project.R/R/censobr/data_release_v0.3.0/2010_tracts_Domicilio_v0.3.0.parquet")'
Execution halted

* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: 1 ERROR, 2 WARNINGs
```

Looks like the same error as in https://github.com/ipeaGIT/geobr/issues/368
Possibly related to endianness assumed wrong without checking.

**Comment by rafapereirabr** [comment]
Most data sets we download with {censobr} are quite large. Some files are over 700 MB. This means the download time can be a bit long depending on internet connection. If the connection becomes unstable while downloading the data set, the local file becomes corrupted. This is kind of expected to happen. This is why the function throws an informative message:

> "Error: File cached locally seems to be corrupted. Please download it again using 'cache = FALSE'.
Alternatively, you can remove the corrupted file with 'censobr::censobr_cache(delete_file = file_name)'"

So, this is not so much of an unexpected error, hence the informative message. Unfortunately, though, this error can occur during CMD checks. 

I'm think I might find a way to solve this issue soon.

**Comment by barracuda156** [comment]
@rafapereirabr Got it, thank you for clarifying. I think in MacPorts we rather not force users download ~1 GB of data even if that would work reliably, so we can keep vignettes disabled.

**Comment by rafapereirabr** [comment]
Hi @barracuda156 . The thing is {censobr} is a package intented to help users *download* and and read Brazilian census data. Unfortunately, a few files are quite big and there is not much we can do further to compress them.

I have now implemented in the dev version a different method to download and check the integrity of the file. So the function will make sure to either download an uncorrupted file OR to throw a message saying the file was not downloaded. I think this should solve this issue.

**Comment by rafapereirabr** [comment]
new version v0.4.0 now on CRAN should solve this.

**Comment by barracuda156** [comment]
@rafapereirabr Thank you, I am running tests for it now. Will update soon.

**Comment by barracuda156** [comment]
Ok, I am still getting errors here:
```
--->  Testing R-censobr
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-censobr/R-censobr/work/censobr" && /opt/local/bin/R CMD check ./censobr_0.4.0.tar.gz --no-manual --no-build-vignettes 
* using log directory ‘/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_R_R-censobr/R-censobr/work/censobr/censobr.Rcheck’
* using R version 4.4.1 (2024-06-14)
* using platform: powerpc-apple-darwin10.0.0d2 (32-bit)
* R was compiled by
    gcc-mp-13 (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0
    GNU Fortran (MacPorts gcc13 13.3.0_0+stdlib_flag) 13.3.0
* running under: OS X Snow Leopard 10.6
* using session charset: UTF-8
* using options ‘--no-manual --no-build-vignettes’
* checking for file ‘censobr/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘censobr’ version ‘0.4.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘censobr’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking code files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking whether startup messages can be suppressed ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes ... OK
* checking running R code from vignettes ...
  ‘censobr.Rmd’ using ‘UTF-8’... failed
  ‘census_tracts_data.Rmd’ using ‘UTF-8’... failed
  ‘documentation.Rmd’ using ‘UTF-8’... OK
  ‘larger_than_memory.Rmd’ using ‘UTF-8’... failed
 ERROR
Errors in running code in vignettes:
when running code in ‘censobr.Rmd’
  ...
> library(ggplot2)

> pop <- read_population(year = 2010, columns = c("abbrev_state", 
+     "V0606", "V0010", "V6400"), add_labels = "pt", showProgress = FALSE)
Downloading data and storing it locally for future use.

  When sourcing ‘censobr.R’:
Error: File cached locally seems to be corrupted. Please download it again using 'cache = FALSE'.
Alternatively, you can remove the corrupted file with 'censobr::censobr_cache(delete_file = "2010_population_v0.3.0.parquet")'
Execution halted
when running code in ‘census_tracts_data.Rmd’
  ...
> library(censobr)

> dom <- read_tracts(year = 2010, dataset = "Domicilio", 
+     showProgress = FALSE)
Downloading data and storing it locally for future use.

  When sourcing ‘census_tracts_data.R’:
Error: File cached locally seems to be corrupted. Please download it again using 'cache = FALSE'.
Alternatively, you can remove the corrupted file with 'censobr::censobr_cache(delete_file = "2010_tracts_Domicilio_v0.3.0.parquet")'
Execution halted
when running code in ‘larger_than_memory.Rmd’
  ...
> library(censobr)

> df <- censobr::read_mortality(year = 2010, add_labels = "pt", 
+     showProgress = FALSE)
Downloading data and storing it locally for future use.

  When sourcing ‘larger_than_memory.R’:
Error: File cached locally seems to be corrupted. Please download it again using 'cache = FALSE'.
Alternatively, you can remove the corrupted file with 'censobr::censobr_cache(delete_file = "2010_mortality_v0.3.0.parquet")'
Execution halted

* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: 1 ERROR
```
But I guess no big deal, we can just keep vignettes disabled in MacPorts.

**Comment by rafapereirabr** [comment]
thanks for the heads up. Does MacPorts put a maximum limit to the size of the files that can be downloaded ?

**Comment by barracuda156** [comment]
> thanks for the heads up. Does MacPorts put a maximum limit to the size of the files that can be downloaded ?

TBH no idea. But I do not think there is a specific restriction.

**Comment by rafapereirabr** [comment]
This message is printed in the following cases:
- there is no internet connection
- the was an issue during the download process and the local file was corrupted

Also , note that due to the large data sets downloaded by the package and long testing time, we disable the vignttes from running on CRAN with:
```
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = identical(tolower(Sys.getenv("NOT_CRAN")), "true"),
  out.width = "100%"
)
```

perhaps what you're finding could be related to this ?
